apiVersion: platform.kratix.io/v1alpha1
kind: Promise
metadata:
  creationTimestamp: null
  name: sql
  namespace: default
spec:
  api:
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: sql.marketplace.kratix.io
    spec:
      group: marketplace.kratix.io
      names:
        kind: sql
        plural: sql
        singular: sql
      scope: Namespaced
      versions:
        - name: v1alpha1
          schema:
            openAPIV3Schema:
              properties:
                spec:
                  properties:
                    size:
                      default: small
                      description: |
                        Size of this sql deployment
                      pattern: ^(small|large)$
                      type: string
                  type: object
              type: object
          served: true
          storage: true
  workflows:
    resource:
      configure:
        - apiVersion: platform.kratix.io/v1alpha1
          kind: Pipeline
          metadata:
            name: instance-configure
            namespace: default
          spec:
            containers:
              - image: ghcr.io/syntasso/kratix-marketplace/sql-configure-pipeline:v0.1.0
                name: sql-configure-pipeline
      delete:
        - apiVersion: platform.kratix.io/v1alpha1
          kind: Pipeline
          metadata:
            name: instance-delete
            namespace: default
          spec:
            containers:
              - image: ghcr.io/syntasso/kratix-marketplace/sql-configure-pipeline:v0.1.0
                name: sql-delete-pipeline
status: {}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sql-resource-pipeline-credentials
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  resourceNames:
  - gcp-credentials
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sql-resource-pipeline-credentials
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sql-resource-pipeline-credentials
subjects:
- kind: ServiceAccount
  name: sql-resource-pipeline
  namespace: default
