apiVersion: platform.kratix.io/v1alpha1
kind: Promise
metadata:
  name: dapr
  namespace: default
spec:
  workerClusterResources:
  - apiVersion: helm.toolkit.fluxcd.io/v2beta1
    kind: HelmRelease
    metadata:
      name: dapr
      namespace: default
    spec:
      releaseName: dapr
      chart:
        spec:
          chart: dapr
          sourceRef:
            kind: HelmRepository
            name: dapr
            namespace: default
      interval: 5m
  - apiVersion: source.toolkit.fluxcd.io/v1beta1
    kind: HelmRepository
    metadata:
      name: dapr
      namespace: default
    spec:
      interval: 5m0s
      url: https://dapr.github.io/helm-charts/
