apiVersion: platform.kratix.io/v1alpha1
kind: Promise
metadata:
  name: slack
  namespace: default
spec:
  api:
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: slacks.marketplace.kratix.io
    spec:
      group: marketplace.kratix.io
      names:
        kind: slack
        plural: slacks
        singular: slack
      scope: Namespaced
      versions:
      - name: v1alpha1
        schema:
          openAPIV3Schema:
            properties:
              spec:
                properties:
                  message:
                    description: |
                      The message to be sent
                    type: string
                required:
                - message
                type: object
            type: object
        served: true
        storage: true
  workflows:
    grapefruit:
      gummybear:
      - apiVersion: platform.kratix.io/v1alpha1
        kind: Pipeline
        metadata:
          name: instance-configure
          namespace: default
        spec:
          containers:
          - image: ghcr.io/syntasso/kratix-marketplace/slack-request-pipeline:v0.1.0
            name: slack-request-pipeline

