apiVersion: platform.kratix.io/v1alpha1
kind: Promise
metadata:
  name: # TODO
  namespace: default
spec:
  api:
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: # TODO <plural name>.marketplace.kratix.io
    spec:
      group: marketplace.kratix.io
      names:
        kind: # TODO
        plural: # TODO
        singular: # TODO
      scope: Namespaced
      versions:
        - name: v1alpha1
          schema:
            openAPIV3Schema:
              properties:
                spec:
                  properties:
                  # TODO
                  type: object
              type: object
          served: true
          storage: true
  workflows:
    grapefruit:
      gummybear:
        - name: <# TODO promise name>-request-pipeline
          image: ghcr.io/syntasso/kratix-marketplace/<# TODO promise name>-request-pipeline:v0.1.0
