apiVersion: v1
kind: Namespace
metadata:
  name: dex
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: dex
  name: dex
  namespace: dex
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dex
rules:
- apiGroups:
  - dex.coreos.com
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dex
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dex
subjects:
- kind: ServiceAccount
  name: dex
  namespace: dex
---
apiVersion: v1
data:
  config.yaml: |
    issuer: https://localhost:32000
    storage:
      type: kubernetes
      config:
        inCluster: true
    web:
      https: 0.0.0.0:5556
      tlsCert: /etc/dex/tls/tls.crt
      tlsKey: /etc/dex/tls/tls.key
    connectors:
    - type: github
      id: github
      name: GitHub
      config:
        clientID: $GITHUB_CLIENT_ID
        clientSecret: $GITHUB_CLIENT_SECRET
        redirectURI: https://localhost:32000/callback
        loadAllGroups: true
    staticClients:
    - id: kube
      redirectURIs:
      - http://localhost:8000
      - http://localhost:18000
      name: kubernetes
      secret: ZXhhbXBsZS1hcHAtc2VjcmV0
kind: ConfigMap
metadata:
  name: dex
  namespace: dex
---
apiVersion: v1
kind: Service
metadata:
  name: dex
  namespace: dex
spec:
  ports:
  - name: dex
    nodePort: 32000
    port: 5556
    protocol: TCP
    targetPort: 5556
  selector:
    app: dex
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dex
  name: dex
  namespace: dex
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dex
  template:
    metadata:
      labels:
        app: dex
    spec:
      containers:
      - command:
        - /usr/local/bin/dex
        - serve
        - /etc/dex/cfg/config.yaml
        env:
        - name: GITHUB_CLIENT_ID
          valueFrom:
            secretKeyRef:
              key: client-id
              name: github-client
        - name: GITHUB_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: client-secret
              name: github-client
        image: ghcr.io/dexidp/dex:v2.30.0
        name: dex
        ports:
        - containerPort: 5556
          name: https
        readinessProbe:
          httpGet:
            path: /healthz
            port: 5556
            scheme: HTTPS
        volumeMounts:
        - mountPath: /etc/dex/cfg
          name: config
        - mountPath: /etc/dex/tls
          name: tls
      serviceAccountName: dex
      volumes:
      - configMap:
          items:
          - key: config.yaml
            path: config.yaml
          name: dex
        name: config
      - name: tls
        secret:
          secretName: dex.example.com.tls
