apiVersion: platform.kratix.io/v1alpha1
kind: Promise
metadata:
  name: namespace
  namespace: default
spec:
  api:
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: namespaces.marketplace.kratix.io
    spec:
      group: marketplace.kratix.io
      names:
        kind: namespace
        plural: namespaces
        singular: namespace
      scope: Namespaced
      versions:
        - name: v1alpha1
          schema:
            openAPIV3Schema:
              properties:
                spec:
                  properties:
                    namespaceName:
                      description: |
                        The name of the namespace to be created
                      type: string
                  required:
                    - namespaceName
                  type: object
              type: object
          served: true
          storage: true
  workflows:
    resource:
      configure:
        - apiVersion: platform.kratix.io/v1alpha1
          kind: Pipeline
          metadata:
            name: approval-gate
            namespace: default
          spec:
            containers:
              - image: ghcr.io/syntasso/kratix-marketplace/pipeline-github-sign-off-image:v0.1.0
                name: create-issue
                command: [ "create-issue" ]
                env:
                - name: GITHUB_REPOSITORY
                  value: kirederik/playground
                - name: GITHUB_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: github-token
                      key: token
        - apiVersion: platform.kratix.io/v1alpha1
          kind: Pipeline
          metadata:
            name: instance-configure
            namespace: default
          spec:
            containers:
              - image: ghcr.io/syntasso/kratix-marketplace/pipeline-github-sign-off-image:v0.1.0
                name: wait-approval
                command: [ "wait-approval" ]
                env:
                - name: GITHUB_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: github-token
                      key: token
              - image: ghcr.io/syntasso/kratix-pipeline-utility:v0.0.1
                name: namespace-configure-pipeline
                command: ["sh"]
                args:
                  - -c
                  - |
                    set -eux
                    approval=$(cat /kratix/metadata/approval-state)
                    if [ "${approval}" == "approved" ]; then
                      kubectl create namespace $(yq '.spec.namespaceName' /kratix/input/object.yaml) --dry-run=client -o yaml > /kratix/output/namespace.yaml
                      exit 0
                    fi

                    echo "message: Approval not granted; requested namespace not created." > /kratix/metadata/status.yaml


