apiVersion: platform.kratix.io/v1alpha1
kind: Promise
metadata:
  creationTimestamp: null
  name: mongodb
spec:
  api:
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: mongodbs.promise.kratix.io
    spec:
      group: promise.kratix.io
      names:
        kind: MongoDB
        listKind: MongoDBList
        plural: mongodbs
        singular: mongodb
      scope: Namespaced
      versions:
      - name: v1alpha1
        schema:
          openAPIV3Schema:
            properties:
              spec:
                properties:
                  majorVersion:
                    default: 6
                    type: number
                  version:
                    type: string
                type: object
            type: object
        served: true
        storage: true
  destinationSelectors:
  - matchLabels:
      environment: dev
  workflows:
    promise:
      configure:
      - apiVersion: platform.kratix.io/v1alpha1
        kind: Pipeline
        metadata:
          name: configure-promise
        spec:
          containers:
          - image: ghcr.io/syntasso/kratix-marketplace/mongodb-deps-configure-pipeline:v0.1.0
            name: mongodb-deps
    resource:
      configure:
      - apiVersion: platform.kratix.io/v1alpha1
        kind: Pipeline
        metadata:
          name: configure-workflow
        spec:
          containers:
          - image: ghcr.io/syntasso/kratix-marketplace/mongodb-configure-pipeline:v0.1.0
            name: create-instance
status: {}
