---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: NAME-backup-pvc-jenkins
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: jenkins.io/v1alpha2
kind: Jenkins
metadata:
  name: prod-NAME
  namespace: default
spec:
  configurationAsCode:
    configurations: []
    secret:
      name: ""
  groovyScripts:
    configurations: []
    secret:
      name: ""
  jenkinsAPISettings:
    authorizationStrategy: createUser
  master:
    basePlugins: # Must be set because operator defaults are out of date
      - name: kubernetes
        version: "1.31.3"
      - name: workflow-job
        version: "1180.v04c4e75dce43"
      - name: workflow-aggregator
        version: "2.7"
      - name: git
        version: "4.11.0"
      - name: job-dsl
        version: "1.79"
      - name: configuration-as-code
        version: "1414.v878271fc496f"
      - name: kubernetes-credentials-provider
        version: "0.20"
    disableCSRFProtection: false
    securityContext:
      runAsUser: 1000
      fsGroup: 1000
    containers:
    - name: jenkins-master
      image: jenkins/jenkins:2.332.2-jdk17
      imagePullPolicy: Always
      command: # Required workaround until https://github.com/jenkinsci/kubernetes-operator/pull/784
        - bash
        - -c
        - /var/jenkins/scripts/init.sh && /usr/bin/tini -s -- /usr/local/bin/jenkins.sh
      env:
        - name: JAVA_OPTS
          value: -Xmx125m -XX:MinRAMPercentage=50.0 -XX:MaxRAMPercentage=80.0 -Djenkins.install.runSetupWizard=false -Djava.awt.headless=true
      livenessProbe:
        failureThreshold: 12
        httpGet:
          path: /login
          port: http
          scheme: HTTP
        initialDelaySeconds: 100
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 5
      readinessProbe:
        failureThreshold: 10
        httpGet:
          path: /login
          port: http
          scheme: HTTP
        initialDelaySeconds: 80
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
      resources:
        limits:
          cpu: 1500m
          memory: 3Gi
        requests:
          cpu: "1"
          memory: 500Mi
    - name: backup-promise
      env:
      - name: BACKUP_DIR
        value: /backup
      - name: JENKINS_HOME
        value: /jenkins-home
      - name: BACKUP_COUNT
        value: "3"
      image: virtuslab/jenkins-operator-backup-pvc:v0.1.1
      imagePullPolicy: IfNotPresent
      volumeMounts:
      - mountPath: /jenkins-home # Jenkins home volume
        name: jenkins-home
      - mountPath: /backup
        name: backup
      resources:
        limits:
          cpu: 1500m
          memory: 3Gi
        requests:
          cpu: "1"
          memory: 500Mi
    volumes:
    - name: backup
      persistentVolumeClaim:
        claimName: NAME-backup-pvc-jenkins
  backup:
    containerName: backup-promise
    action:
      exec:
        command:
        - /home/user/bin/backup.sh
    interval: 30
    makeBackupBeforePodDeletion: true
  restore:
    containerName: backup-promise
    action:
      exec:
        command:
        - /home/user/bin/restore.sh
    getLatestAction:
      exec:
        command:
        - /home/user/bin/get-latest.sh