---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: CLUSTERNAME-resources
  namespace: CLUSTERNAME
spec:
  interval: 3s
  prune: true
  dependsOn:
    - name: CLUSTERNAME-dependencies
  sourceRef:
    kind: Bucket
    name: kratix
    namespace: flux-system
  path: ./CLUSTERNAME/resources
  kubeConfig:
    secretRef:
      name: vc-CLUSTERNAME-flux
      key: config
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: CLUSTERNAME-dependencies
  namespace: CLUSTERNAME
spec:
  interval: 8s
  prune: true
  sourceRef:
    kind: Bucket
    name: kratix
    namespace: flux-system
  path: ./CLUSTERNAME/dependencies
  kubeConfig:
    secretRef:
      name: vc-CLUSTERNAME-flux
      key: config
