version: 2.1

executors:
  my-executor:
    docker:
      - image: cimg/base:2022.09

jobs:
  noop:
    executor: my-executor
    steps:
      - run: echo "No changes in promises detected!"

workflows:
  noop:
    jobs:
      - noop
